services:
  postgres_ad:
    image: postgres:17.5
    container_name: postgres_ad
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-ad-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - local-network-ad
  pgadmin_ad:
    image: dpage/pgadmin4:9.5
    container_name: pgadmin_ad
    depends_on:
      - postgres_ad
    environment:
      PGADMIN_DEFAULT_EMAIL: dba@algadelivery.com
      PGADMIN_DEFAULT_PASSWORD: algadelivery
    ports:
      - 8083:80
    volumes:
      - pgadmin-ad-data:/var/lib/pgadmin
    networks:
      - local-network-ad
  kafka_ad:
    image: apache/kafka:4.1.1
    container_name: kafka_ad
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_ad:9090,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka_ad:9091
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 #Valor padrão para replicação dos tópicos
    volumes:
      - kafka-ad-data:/apache/kafka
    networks:
      - local-network-ad
  kafka-ui_ad:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui_ad
    ports:
      - 8084:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: algadelivery-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka_ad:9090
    networks:
      - local-network-ad
volumes:
  postgres-ad-data:
  pgadmin-ad-data:
  kafka-ad-data:
networks:
  local-network-ad:
    driver: bridge